server:
  port: 8081
spring:
  application:
    name: js-consumer-deposit
#  zipkin: #追踪
#    base-url: http://localhost:7700
  sleuth:
    sampler:
      percentage: 1.0
  thymeleaf:
    prefix: classpath:/public/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
eureka:
  client:
    service-url:
      defaultZone: http://39.105.144.187:6001/eureka/
feign:
  hystrix:
    enabled: true
dm-spring-provider-zhanghu:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level: info
