server:
  port: 6001
eureka:
  client:
    service-url:
      defaluZone: 39.105.144.187:6001/eureka/
    fetch-registry: false
    register-with-eureka: false
  server:
    renewal-percent-threshold: 0.49
security:
  basic:
    enabled: true
  user:
    name: root
    password: root